// Generated by scripts/version.ts - do not edit by hand.
// Regenerate with: bun run build:prod
import type { BuildInfo } from '../../shared/build-info.ts'

export const BUILD_INFO: BuildInfo = {
  version: '0.4.0',
  commit: '9ba964c-dirty',
  dirty: true,
}
